[package]
name = "cat-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10.0"
log = "0.4.17"
rand = "0.8.5"
serenity = "0.11.5"
thiserror = "1.0.38"
tokio = {version = "1.24.2", features=["rt-multi-thread"]}
